spring:
  profiles:
    active: dev
---
server:
  port: 8201  
spring:
  profiles: dev
  application:
    name: provider-dept #服务名称（确定是否为同一服务）
eureka:
  client:
    service-url: #注册中心
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: provider-dept #服务名称（确定是否为同一服务）
eureka:
  client:
    service-url: #注册中心
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/